/*
 * The following C code was generated by barectf 2.1.0-dev
 * on 2016-03-15T21:29:16.070651.
 *
 * For more details, see <https://github.com/efficios/barectf>.
 */

#include <stdint.h>
#include <string.h>
#include <assert.h>

#include "barectf.h"

#define _ALIGN(_at, _align)				\
	do {						\
		(_at) = ((_at) + ((_align) - 1)) & -(_align);	\
	} while (0)

#define _BITS_TO_BYTES(_x)	((_x) >> 3)
#define _BYTES_TO_BITS(_x)	((_x) << 3)

union f2u {
	float f;
	uint32_t u;
};

union d2u {
	double f;
	uint64_t u;
};

uint32_t barectf_packet_size(void *ctx)
{
	return ((struct barectf_ctx *) ctx)->packet_size;
}

int barectf_packet_is_full(void *ctx)
{
	struct barectf_ctx *cctx = ctx;

	return cctx->at == cctx->packet_size;
}

int barectf_packet_is_empty(void *ctx)
{
	struct barectf_ctx *cctx = ctx;

	return cctx->at <= cctx->off_content;
}

uint32_t barectf_packet_events_discarded(void *ctx)
{
	return ((struct barectf_ctx *) ctx)->events_discarded;
}

uint8_t *barectf_packet_buf(void *ctx)
{
	return ((struct barectf_ctx *) ctx)->buf;
}

uint32_t barectf_packet_buf_size(void *ctx)
{
	return _BITS_TO_BYTES(((struct barectf_ctx *) ctx)->packet_size);
}

void barectf_packet_set_buf(void *ctx, uint8_t *buf, uint32_t buf_size)
{
	struct barectf_ctx *barectf_ctx = ctx;

	barectf_ctx->buf = buf;
	barectf_ctx->packet_size = _BYTES_TO_BITS(buf_size);
}

int barectf_packet_is_open(void *ctx)
{
	return ((struct barectf_ctx *) ctx)->packet_is_open;
}

static
void _write_cstring(struct barectf_ctx *ctx, const char *src)
{
	uint32_t sz = strlen(src) + 1;

	memcpy(&ctx->buf[_BITS_TO_BYTES(ctx->at)], src, sz);
	ctx->at += _BYTES_TO_BITS(sz);
}

static inline
int _packet_is_full(struct barectf_ctx *ctx)
{
	return barectf_packet_is_full(ctx);
}

static
int _reserve_event_space(struct barectf_ctx *ctx, uint32_t ev_size)
{
	/* event _cannot_ fit? */
	if (ev_size > (ctx->packet_size - ctx->off_content)) {
		ctx->events_discarded++;

		return 0;
	}

	/* packet is full? */
	if (barectf_packet_is_full(ctx)) {
		/* yes: is back-end full? */
		if (ctx->cbs.is_backend_full(ctx->data)) {
			/* yes: discard event */
			ctx->events_discarded++;

			return 0;
		}

		/* back-end is not full: open new packet */
		ctx->cbs.open_packet(ctx->data);
	}

	/* event fits the current packet? */
	if (ev_size > (ctx->packet_size - ctx->at)) {
		/* no: close packet now */
		ctx->cbs.close_packet(ctx->data);

		/* is back-end full? */
		if (ctx->cbs.is_backend_full(ctx->data)) {
			/* yes: discard event */
			ctx->events_discarded++;

			return 0;
		}

		/* back-end is not full: open new packet */
		ctx->cbs.open_packet(ctx->data);
		assert(ev_size <= (ctx->packet_size - ctx->at));
	}

	return 1;
}

static
void _commit_event(struct barectf_ctx *ctx)
{
	/* is packet full? */
	if (barectf_packet_is_full(ctx)) {
		/* yes: close it now */
		ctx->cbs.close_packet(ctx->data);
	}
}

/* initialize context */
void barectf_init(
	void *ctx,
	uint8_t *buf,
	uint32_t buf_size,
	struct barectf_platform_callbacks cbs,
	void *data
)
{
	struct barectf_ctx *barectf_ctx = ctx;
	barectf_ctx->cbs = cbs;
	barectf_ctx->data = data;
	barectf_ctx->buf = buf;
	barectf_ctx->packet_size = _BYTES_TO_BITS(buf_size);
	barectf_ctx->at = 0;
	barectf_ctx->events_discarded = 0;
	barectf_ctx->packet_is_open = 0;
}

/* open packet for stream "default" */
void barectf_default_open_packet(
	struct barectf_default_ctx *ctx
)
{
	uint64_t ts = ctx->parent.cbs.default_clock_get_value(ctx->parent.data);

	/* do not open a packet that is already open */
	if (ctx->parent.packet_is_open) {
		return;
	}

	ctx->parent.at = 0;

	/* trace packet header */
	{
		/* align structure */
		_ALIGN(ctx->parent.at, 8);

		/* "magic" field */
		_ALIGN(ctx->parent.at, 8);
		barectf_bt_bitfield_write_le(&(&ctx->parent)->buf[_BITS_TO_BYTES((&ctx->parent)->at)], uint8_t, 0, 32, 0xc1fc1fc1UL);
		(&ctx->parent)->at += 32;

		/* "uuid" field */
		{
			static uint8_t uuid[] = {
				127,
				53,
				26,
				32,
				235,
				22,
				17,
				229,
				140,
				48,
				36,
				119,
				3,
				138,
				62,
				196,
			};

			_ALIGN(ctx->parent.at, 8);
			memcpy(&ctx->parent.buf[_BITS_TO_BYTES(ctx->parent.at)], uuid, 16);
			ctx->parent.at += _BYTES_TO_BITS(16);
		}

		/* "stream_id" field */
		_ALIGN(ctx->parent.at, 8);
		barectf_bt_bitfield_write_le(&(&ctx->parent)->buf[_BITS_TO_BYTES((&ctx->parent)->at)], uint8_t, 0, 8, (uint8_t) 0);
		(&ctx->parent)->at += 8;
	}

	/* stream packet context */
	{
		/* align structure */
		_ALIGN(ctx->parent.at, 8);

		/* "timestamp_begin" field */
		_ALIGN(ctx->parent.at, 8);
		barectf_bt_bitfield_write_le(&(&ctx->parent)->buf[_BITS_TO_BYTES((&ctx->parent)->at)], uint8_t, 0, 64, (uint64_t) ts);
		(&ctx->parent)->at += 64;

		/* "timestamp_end" field */
		_ALIGN(ctx->parent.at, 8);
		ctx->off_spc_timestamp_end = ctx->parent.at;
		ctx->parent.at += 64;

		/* "packet_size" field */
		_ALIGN(ctx->parent.at, 8);
		barectf_bt_bitfield_write_le(&(&ctx->parent)->buf[_BITS_TO_BYTES((&ctx->parent)->at)], uint8_t, 0, 32, (uint32_t) ctx->parent.packet_size);
		(&ctx->parent)->at += 32;

		/* "content_size" field */
		_ALIGN(ctx->parent.at, 8);
		ctx->off_spc_content_size = ctx->parent.at;
		ctx->parent.at += 32;

		/* "events_discarded" field */
		_ALIGN(ctx->parent.at, 8);
		ctx->off_spc_events_discarded = ctx->parent.at;
		ctx->parent.at += 32;
	}

	ctx->parent.off_content = ctx->parent.at;

	/* mark current packet as open */
	ctx->parent.packet_is_open = 1;
}

/* close packet for stream "default" */
void barectf_default_close_packet(struct barectf_default_ctx *ctx)
{
	uint64_t ts = ctx->parent.cbs.default_clock_get_value(ctx->parent.data);

	/* do not close a packet that is not open */
	if (!ctx->parent.packet_is_open) {
		return;
	}

	/* save content size */
	ctx->parent.content_size = ctx->parent.at;

	/* "timestamp_end" field */
	ctx->parent.at = ctx->off_spc_timestamp_end;
	barectf_bt_bitfield_write_le(&(&ctx->parent)->buf[_BITS_TO_BYTES((&ctx->parent)->at)], uint8_t, 0, 64, (uint64_t) ts);
	(&ctx->parent)->at += 64;

	/* "content_size" field */
	ctx->parent.at = ctx->off_spc_content_size;
	barectf_bt_bitfield_write_le(&(&ctx->parent)->buf[_BITS_TO_BYTES((&ctx->parent)->at)], uint8_t, 0, 32, (uint32_t) ctx->parent.content_size);
	(&ctx->parent)->at += 32;

	/* "events_discarded" field */
	ctx->parent.at = ctx->off_spc_events_discarded;
	barectf_bt_bitfield_write_le(&(&ctx->parent)->buf[_BITS_TO_BYTES((&ctx->parent)->at)], uint8_t, 0, 32, (uint32_t) ctx->parent.events_discarded);
	(&ctx->parent)->at += 32;

	/* go back to end of packet */
	ctx->parent.at = ctx->parent.packet_size;

	/* mark packet as closed */
	ctx->parent.packet_is_open = 0;
}

static void _serialize_stream_event_header_default(
	struct barectf_ctx *ctx,
	uint32_t event_id
)
{
	uint64_t ts = ctx->cbs.default_clock_get_value(ctx->data);

	{
		/* align structure */
		_ALIGN(ctx->at, 8);

		/* "timestamp" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 64, (uint64_t) ts);
		ctx->at += 64;

		/* "id" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 16, (uint16_t) event_id);
		ctx->at += 16;
	}

}

static uint32_t _get_event_size_default_simple_uint32(
	struct barectf_ctx *ctx,
	uint32_t ep_value
)
{
	uint32_t at = ctx->at;

	/* stream event header */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "timestamp" field */
		_ALIGN(at, 8);
		at += 64;

		/* "id" field */
		_ALIGN(at, 8);
		at += 16;
	}

	/* event payload */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "value" field */
		_ALIGN(at, 8);
		at += 32;
	}

	return at - ctx->at;
}

static void _serialize_event_default_simple_uint32(
	struct barectf_ctx *ctx,
	uint32_t ep_value
)
{
	/* stream event header */
	_serialize_stream_event_header_default(ctx, 0);

	/* event payload */
	{
		/* align structure */
		_ALIGN(ctx->at, 8);

		/* "value" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 32, ep_value);
		ctx->at += 32;
	}

}

/* trace (stream "default", event "simple_uint32") */
void barectf_default_trace_simple_uint32(
	struct barectf_default_ctx *ctx,
	uint32_t ep_value
)
{
	uint32_t ev_size;

	/* get event size */
	ev_size = _get_event_size_default_simple_uint32((void *) ctx, ep_value);

	/* do we have enough space to serialize? */
	if (!_reserve_event_space((void *) ctx, ev_size)) {
		/* no: forget this */
		return;
	}

	/* serialize event */
	_serialize_event_default_simple_uint32((void *) ctx, ep_value);

	/* commit event */
	_commit_event((void *) ctx);
}

static uint32_t _get_event_size_default_simple_int16(
	struct barectf_ctx *ctx,
	int16_t ep_value
)
{
	uint32_t at = ctx->at;

	/* stream event header */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "timestamp" field */
		_ALIGN(at, 8);
		at += 64;

		/* "id" field */
		_ALIGN(at, 8);
		at += 16;
	}

	/* event payload */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "value" field */
		_ALIGN(at, 8);
		at += 16;
	}

	return at - ctx->at;
}

static void _serialize_event_default_simple_int16(
	struct barectf_ctx *ctx,
	int16_t ep_value
)
{
	/* stream event header */
	_serialize_stream_event_header_default(ctx, 1);

	/* event payload */
	{
		/* align structure */
		_ALIGN(ctx->at, 8);

		/* "value" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 16, ep_value);
		ctx->at += 16;
	}

}

/* trace (stream "default", event "simple_int16") */
void barectf_default_trace_simple_int16(
	struct barectf_default_ctx *ctx,
	int16_t ep_value
)
{
	uint32_t ev_size;

	/* get event size */
	ev_size = _get_event_size_default_simple_int16((void *) ctx, ep_value);

	/* do we have enough space to serialize? */
	if (!_reserve_event_space((void *) ctx, ev_size)) {
		/* no: forget this */
		return;
	}

	/* serialize event */
	_serialize_event_default_simple_int16((void *) ctx, ep_value);

	/* commit event */
	_commit_event((void *) ctx);
}

static uint32_t _get_event_size_default_simple_float(
	struct barectf_ctx *ctx,
	float ep_value
)
{
	uint32_t at = ctx->at;

	/* stream event header */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "timestamp" field */
		_ALIGN(at, 8);
		at += 64;

		/* "id" field */
		_ALIGN(at, 8);
		at += 16;
	}

	/* event payload */
	{
		/* align structure */
		_ALIGN(at, 32);

		/* "value" field */
		_ALIGN(at, 32);
		at += 32;
	}

	return at - ctx->at;
}

static void _serialize_event_default_simple_float(
	struct barectf_ctx *ctx,
	float ep_value
)
{
	/* stream event header */
	_serialize_stream_event_header_default(ctx, 2);

	/* event payload */
	{
		/* align structure */
		_ALIGN(ctx->at, 32);

		/* "value" field */
		_ALIGN(ctx->at, 32);
		union f2u f2u;

		f2u.f = ep_value;
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 32, f2u.u);
		ctx->at += 32;
	}

}

/* trace (stream "default", event "simple_float") */
void barectf_default_trace_simple_float(
	struct barectf_default_ctx *ctx,
	float ep_value
)
{
	uint32_t ev_size;

	/* get event size */
	ev_size = _get_event_size_default_simple_float((void *) ctx, ep_value);

	/* do we have enough space to serialize? */
	if (!_reserve_event_space((void *) ctx, ev_size)) {
		/* no: forget this */
		return;
	}

	/* serialize event */
	_serialize_event_default_simple_float((void *) ctx, ep_value);

	/* commit event */
	_commit_event((void *) ctx);
}

static uint32_t _get_event_size_default_simple_string(
	struct barectf_ctx *ctx,
	const char * ep_value
)
{
	uint32_t at = ctx->at;

	/* stream event header */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "timestamp" field */
		_ALIGN(at, 8);
		at += 64;

		/* "id" field */
		_ALIGN(at, 8);
		at += 16;
	}

	/* event payload */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "value" field */
		_ALIGN(at, 8);
		at += _BYTES_TO_BITS(strlen(ep_value) + 1);
	}

	return at - ctx->at;
}

static void _serialize_event_default_simple_string(
	struct barectf_ctx *ctx,
	const char * ep_value
)
{
	/* stream event header */
	_serialize_stream_event_header_default(ctx, 3);

	/* event payload */
	{
		/* align structure */
		_ALIGN(ctx->at, 8);

		/* "value" field */
		_ALIGN(ctx->at, 8);
		_write_cstring(ctx, ep_value);
	}

}

/* trace (stream "default", event "simple_string") */
void barectf_default_trace_simple_string(
	struct barectf_default_ctx *ctx,
	const char * ep_value
)
{
	uint32_t ev_size;

	/* get event size */
	ev_size = _get_event_size_default_simple_string((void *) ctx, ep_value);

	/* do we have enough space to serialize? */
	if (!_reserve_event_space((void *) ctx, ev_size)) {
		/* no: forget this */
		return;
	}

	/* serialize event */
	_serialize_event_default_simple_string((void *) ctx, ep_value);

	/* commit event */
	_commit_event((void *) ctx);
}

static uint32_t _get_event_size_default_simple_enum(
	struct barectf_ctx *ctx,
	uint8_t ep_value
)
{
	uint32_t at = ctx->at;

	/* stream event header */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "timestamp" field */
		_ALIGN(at, 8);
		at += 64;

		/* "id" field */
		_ALIGN(at, 8);
		at += 16;
	}

	/* event payload */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "value" field */
		_ALIGN(at, 8);
		at += 8;
	}

	return at - ctx->at;
}

static void _serialize_event_default_simple_enum(
	struct barectf_ctx *ctx,
	uint8_t ep_value
)
{
	/* stream event header */
	_serialize_stream_event_header_default(ctx, 4);

	/* event payload */
	{
		/* align structure */
		_ALIGN(ctx->at, 8);

		/* "value" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 8, ep_value);
		ctx->at += 8;
	}

}

/* trace (stream "default", event "simple_enum") */
void barectf_default_trace_simple_enum(
	struct barectf_default_ctx *ctx,
	uint8_t ep_value
)
{
	uint32_t ev_size;

	/* get event size */
	ev_size = _get_event_size_default_simple_enum((void *) ctx, ep_value);

	/* do we have enough space to serialize? */
	if (!_reserve_event_space((void *) ctx, ev_size)) {
		/* no: forget this */
		return;
	}

	/* serialize event */
	_serialize_event_default_simple_enum((void *) ctx, ep_value);

	/* commit event */
	_commit_event((void *) ctx);
}

static uint32_t _get_event_size_default_a_few_fields(
	struct barectf_ctx *ctx,
	int32_t ep_int32,
	uint16_t ep_uint16,
	double ep_dbl,
	const char * ep_str,
	uint8_t ep_state
)
{
	uint32_t at = ctx->at;

	/* stream event header */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "timestamp" field */
		_ALIGN(at, 8);
		at += 64;

		/* "id" field */
		_ALIGN(at, 8);
		at += 16;
	}

	/* event payload */
	{
		/* align structure */
		_ALIGN(at, 64);

		/* "int32" field */
		_ALIGN(at, 8);
		at += 32;

		/* "uint16" field */
		_ALIGN(at, 8);
		at += 16;

		/* "dbl" field */
		_ALIGN(at, 64);
		at += 64;

		/* "str" field */
		_ALIGN(at, 8);
		at += _BYTES_TO_BITS(strlen(ep_str) + 1);

		/* "state" field */
		_ALIGN(at, 8);
		at += 8;
	}

	return at - ctx->at;
}

static void _serialize_event_default_a_few_fields(
	struct barectf_ctx *ctx,
	int32_t ep_int32,
	uint16_t ep_uint16,
	double ep_dbl,
	const char * ep_str,
	uint8_t ep_state
)
{
	/* stream event header */
	_serialize_stream_event_header_default(ctx, 5);

	/* event payload */
	{
		/* align structure */
		_ALIGN(ctx->at, 64);

		/* "int32" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 32, ep_int32);
		ctx->at += 32;

		/* "uint16" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 16, ep_uint16);
		ctx->at += 16;

		/* "dbl" field */
		_ALIGN(ctx->at, 64);
		union d2u d2u;

		d2u.f = ep_dbl;
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 64, d2u.u);
		ctx->at += 64;

		/* "str" field */
		_ALIGN(ctx->at, 8);
		_write_cstring(ctx, ep_str);

		/* "state" field */
		_ALIGN(ctx->at, 8);
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 8, ep_state);
		ctx->at += 8;
	}

}

/* trace (stream "default", event "a_few_fields") */
void barectf_default_trace_a_few_fields(
	struct barectf_default_ctx *ctx,
	int32_t ep_int32,
	uint16_t ep_uint16,
	double ep_dbl,
	const char * ep_str,
	uint8_t ep_state
)
{
	uint32_t ev_size;

	/* get event size */
	ev_size = _get_event_size_default_a_few_fields((void *) ctx, ep_int32, ep_uint16, ep_dbl, ep_str, ep_state);

	/* do we have enough space to serialize? */
	if (!_reserve_event_space((void *) ctx, ev_size)) {
		/* no: forget this */
		return;
	}

	/* serialize event */
	_serialize_event_default_a_few_fields((void *) ctx, ep_int32, ep_uint16, ep_dbl, ep_str, ep_state);

	/* commit event */
	_commit_event((void *) ctx);
}

static uint32_t _get_event_size_default_bit_packed_integers(
	struct barectf_ctx *ctx,
	uint8_t ep_uint1,
	int8_t ep_int1,
	uint8_t ep_uint2,
	int8_t ep_int3,
	uint8_t ep_uint4,
	int8_t ep_int5,
	uint8_t ep_uint6,
	int8_t ep_int7,
	uint8_t ep_uint8
)
{
	uint32_t at = ctx->at;

	/* stream event header */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "timestamp" field */
		_ALIGN(at, 8);
		at += 64;

		/* "id" field */
		_ALIGN(at, 8);
		at += 16;
	}

	/* event payload */
	{
		/* align structure */
		_ALIGN(at, 8);

		/* "uint1" field */
		at += 1;

		/* "int1" field */
		at += 1;

		/* "uint2" field */
		at += 2;

		/* "int3" field */
		at += 3;

		/* "uint4" field */
		at += 4;

		/* "int5" field */
		at += 5;

		/* "uint6" field */
		at += 6;

		/* "int7" field */
		at += 7;

		/* "uint8" field */
		at += 8;
	}

	return at - ctx->at;
}

static void _serialize_event_default_bit_packed_integers(
	struct barectf_ctx *ctx,
	uint8_t ep_uint1,
	int8_t ep_int1,
	uint8_t ep_uint2,
	int8_t ep_int3,
	uint8_t ep_uint4,
	int8_t ep_int5,
	uint8_t ep_uint6,
	int8_t ep_int7,
	uint8_t ep_uint8
)
{
	/* stream event header */
	_serialize_stream_event_header_default(ctx, 6);

	/* event payload */
	{
		/* align structure */
		_ALIGN(ctx->at, 8);

		/* "uint1" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 1, ep_uint1);
		ctx->at += 1;

		/* "int1" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 1, 1, ep_int1);
		ctx->at += 1;

		/* "uint2" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 2, 2, ep_uint2);
		ctx->at += 2;

		/* "int3" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 4, 3, ep_int3);
		ctx->at += 3;

		/* "uint4" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 7, 4, ep_uint4);
		ctx->at += 4;

		/* "int5" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 3, 5, ep_int5);
		ctx->at += 5;

		/* "uint6" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 0, 6, ep_uint6);
		ctx->at += 6;

		/* "int7" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 6, 7, ep_int7);
		ctx->at += 7;

		/* "uint8" field */
		barectf_bt_bitfield_write_le(&ctx->buf[_BITS_TO_BYTES(ctx->at)], uint8_t, 5, 8, ep_uint8);
		ctx->at += 8;
	}

}

/* trace (stream "default", event "bit_packed_integers") */
void barectf_default_trace_bit_packed_integers(
	struct barectf_default_ctx *ctx,
	uint8_t ep_uint1,
	int8_t ep_int1,
	uint8_t ep_uint2,
	int8_t ep_int3,
	uint8_t ep_uint4,
	int8_t ep_int5,
	uint8_t ep_uint6,
	int8_t ep_int7,
	uint8_t ep_uint8
)
{
	uint32_t ev_size;

	/* get event size */
	ev_size = _get_event_size_default_bit_packed_integers((void *) ctx, ep_uint1, ep_int1, ep_uint2, ep_int3, ep_uint4, ep_int5, ep_uint6, ep_int7, ep_uint8);

	/* do we have enough space to serialize? */
	if (!_reserve_event_space((void *) ctx, ev_size)) {
		/* no: forget this */
		return;
	}

	/* serialize event */
	_serialize_event_default_bit_packed_integers((void *) ctx, ep_uint1, ep_int1, ep_uint2, ep_int3, ep_uint4, ep_int5, ep_uint6, ep_int7, ep_uint8);

	/* commit event */
	_commit_event((void *) ctx);
}
