# The MIT License (MIT)
#
# Copyright (c) 2016 Philippe Proulx <pproulx@efficios.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

BARECTF ?= barectf
ARCH = arm-none-eabi

RM = rm -rf
MKDIR = mkdir -p
CC = $(ARCH)-gcc

VERSION = qemu-arm-uart
CPU=arm926ej-s
EXTRA_DIR = ../../extra
CFLAGS = -DWITH_QEMU_ARM_UART=1 -ffunction-sections -mcpu=$(CPU) -O2 -Wall -pedantic -I$(EXTRA_DIR) -I.
LDFLAGS= -T barectf-platform-$(VERSION).ld -lc -lnosys

TARGET = barectf-tracepoint-barectf-$(VERSION)
OBJS = $(TARGET).o barectf-$(VERSION).o barectf-platform-$(VERSION).o
TRACEDIR = ctf-$(VERSION)

.PHONY: all clean sim

all: $(TARGET)

$(TRACEDIR):
	$(MKDIR) $@

$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

$(TRACEDIR)/metadata barectf-bitfield.h barectf.h barectf.c: config.yaml $(TRACEDIR)
	$(BARECTF) $< -m $(TRACEDIR)

barectf-$(VERSION).o: barectf.c
	$(CC) -o $@ $(CFLAGS) -c $<

barectf-platform-$(VERSION).o: barectf-platform-$(VERSION).c
	$(CC) $(CFLAGS) -c $<

$(TARGET).o: barectf-tracepoint.c barectf-tracepoint-$(VERSION).h barectf.h barectf-bitfield.h
	$(CC) -o $@ $(CFLAGS) -c $<

clean:
	$(RM) $(TARGET) $(OBJS) $(TRACEDIR)
	$(RM) barectf.h barectf-bitfield.h barectf.c

sim: $(TARGET)
	./barectf-tracepoint-barectf-qemu-arm-uart.sh
