BARECTF ?= barectf
ARCH = arm-none-eabi

RM = rm -rf
MKDIR = mkdir -p
CC = $(ARCH)-gcc

VERSION = qemu-arm-uart
CPU=arm926ej-s
EXTRA_DIR = ../../../extra
CFLAGS = -DWITH_QEMU_ARM_UART=1 -ffunction-sections -mcpu=$(CPU) -O2 -Wall -pedantic -std=gnu99 -I$(EXTRA_DIR) -I.
LDFLAGS= -T barectf-platform-$(VERSION).ld -lc -lnosys

TARGET = barectf-tracepoint-barectf-$(VERSION)
OBJS = $(TARGET).o barectf-$(VERSION).o barectf-platform-$(VERSION).o
TRACEDIR = ctf-$(VERSION)

.PHONY: all clean sim

all: $(TARGET)

$(TRACEDIR):
	$(MKDIR) $@

$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

$(TRACEDIR)/metadata barectf-bitfield.h barectf.h barectf.c: config.yaml $(TRACEDIR)
	$(BARECTF) $< -m $(TRACEDIR)

barectf-$(VERSION).o: barectf.c
	$(CC) -o $@ $(CFLAGS) -c $<

barectf-platform-$(VERSION).o: barectf-platform-$(VERSION).c
	$(CC) $(CFLAGS) -c $<

$(TARGET).o: barectf-tracepoint.c barectf-tracepoint-$(VERSION).h barectf.h barectf-bitfield.h
	$(CC) -o $@ $(CFLAGS) -c $<

clean:
	$(RM) $(TARGET) $(OBJS) $(TRACEDIR)
	$(RM) barectf.h barectf-bitfield.h barectf.c

sim: $(TARGET)
	./barectf-tracepoint-barectf-qemu-arm-uart.sh
